# Generated by Django 4.2.1 on 2023-05-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0003_alter_qr_code_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_urls', models.CharField(max_length=1000)),
                ('alias', models.CharField(max_length=200)),
                ('short_urls', models.CharField(max_length=200)),
            ],
        ),
    ]
