# Generated by Django 4.2.1 on 2023-05-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0004_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='alias',
        ),
    ]
