# Generated by Django 4.2.1 on 2023-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0005_remove_qr_code_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='link',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='long_urls',
            field=models.CharField(max_length=10000),
        ),
    ]
