# Generated by Django 4.2.1 on 2023-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0007_alter_qr_code_link_alter_short_url_long_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Short_url',
        ),
        migrations.AddField(
            model_name='qr_code',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
