# Generated by Django 4.2.1 on 2023-05-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0010_remove_qr_code_alias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QR_code',
            new_name='QRCode',
        ),
        migrations.RenameModel(
            old_name='Url_shortener',
            new_name='URLShortener',
        ),
    ]
