# Generated by Django 4.2.1 on 2023-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0011_rename_qr_code_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
