# Generated by Django 4.2.1 on 2023-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0012_alter_urlshortener_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLShortener',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
