# Generated by Django 4.2.1 on 2023-05-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0013_delete_urlshortener_qrcode_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='alias',
        ),
    ]
