# Generated by Django 4.2.1 on 2023-05-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0016_remove_qr_code_alias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qr_code',
            new_name='QRCode',
        ),
    ]
