# Generated by Django 4.2.1 on 2023-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0017_rename_qr_code_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLshortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('uuid', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='QRCode',
            new_name='QRCodeGenerator',
        ),
    ]
