# Generated by Django 4.2.1 on 2023-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0019_qrcodegenerator_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='uuid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
