# Generated by Django 4.2.1 on 2023-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0020_alter_urlshortener_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
