# Generated by Django 4.2.1 on 2023-05-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0022_remove_urlshortener_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
