# Generated by Django 4.2.1 on 2023-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0023_urlshortener_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='alias',
        ),
    ]
