# Generated by Django 4.2.1 on 2023-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0024_remove_qrcodegenerator_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodegenerator',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
