# Generated by Django 4.2.1 on 2023-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrurl_app', '0027_delete_urlshortener'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('uuid', models.CharField(max_length=20)),
            ],
        ),
    ]
